### ISSUE TITLE
env定义问题

### ISSUE THREAD

**Issue by wengcanbin1** [Livioni/Cloud-Workflow-Scheduling-base-on-Deep-Reinforcement-Learning#4]
我在运行PPOagent的时候显示这个错误，去找clusterEnv文件发现好像没有定义action_space和observation_space。这个可能是错误来源，想请问怎么跑起来呢

报错信息如下

training environment name : clusterEnv-v0
train datasheet lib.
Traceback (most recent call last):
  File "D:/pythonproject/workflow_DRL/PPOagent.py", line 40, in <module>
    env = gym.make(env_name).unwrapped
  File "D:\software\annaconda3\annoconda3\envs\torch\lib\site-packages\gym\envs\registration.py", line 685, in make
    env = PassiveEnvChecker(env)
  File "D:\software\annaconda3\annoconda3\envs\torch\lib\site-packages\gym\wrappers\env_checker.py", line 20, in __init__
    assert hasattr(
AssertionError: The environment must specify an action space. https://www.gymlibrary.ml/content/environment_creation/
load completed.

**Comment by Livioni** [comment]
问题应该出在env = PassiveEnvChecker(env)。gym检测环境的check_env(env) api会检测action_space和observation_space的定义，我当时写代码的时候gym还没有出文档，索性我就没定义动作和状态空间，也能运行，解决方法就是注释掉checkenv的代码，或者根据自己的需求，按照https://www.gymlibrary.ml/content/environment_creation/ 文档在环境中定义动作和状态空间。
